name: Homebrew Install

on:
  pull_request:
    branches:
      - main

concurrency:
  group: homebrew-install-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Homebrew Install
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        runner-image:
          - ubuntu-latest # linux-amd64
          - ubuntu-24.04-arm # linux-arm64
          - macos-latest # darwin-arm64
          - macos-13 # linux-amd64
    runs-on: ${{ matrix.runner-image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Homebrew
        shell: bash
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Homebrew Install Dify
        run: brew install ./dify.rb

      - name: Homebrew Test Dify
        run: brew test dify
